# Generated by Django 3.1.2 on 2020-11-22 22:17

from django.db import migrations, models
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applied_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('project_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Applied',
                'verbose_name_plural': 'Applied',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(auto_created=True, default=None, primary_key=True, serialize=False)),
                ('name', multiselectfield.db.fields.MultiSelectField(choices=[('Cow_Farming', 'Cow_Farming'), ('Goat_Farming', 'Goat_Farming'), ('Fisheries', 'Fisheries'), ('Poultry', 'Poultry'), ('Rice_Farming', 'Rice_Farming'), ('Vegetables_Farming', 'Vegetables_Farming')], default=None, max_length=74)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Land_Data',
            fields=[
                ('project_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('id', models.IntegerField(auto_created=True, default=None)),
                ('title', models.CharField(default=None, max_length=250, null=True)),
                ('slug', models.SlugField(default=None, max_length=250, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(default=None, max_length=250, null=True)),
                ('category_id', models.CharField(default=None, max_length=250, null=True)),
                ('location', models.CharField(default=None, max_length=15, null=True)),
                ('land_img', models.ImageField(blank=True, null=True, upload_to='Land_pic/')),
                ('dolil_img', models.ImageField(blank=True, null=True, upload_to='Land_dolil_pic/')),
                ('khotian_img', models.ImageField(blank=True, null=True, upload_to='Land_khotian_pic/')),
                ('allow_status', models.BooleanField(blank=True, default=None, null=True)),
                ('area', models.IntegerField(blank=True, null=True)),
                ('monthly_charge', models.IntegerField(blank=True, null=True)),
                ('soil_type', models.CharField(default=None, max_length=250, null=True)),
                ('detail_addr', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Land Data',
                'verbose_name_plural': "Land Data's",
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('loc_ver', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('status_ver', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('land_size_ver', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('land_ver_com', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('land_ver_usr', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('doc_ver', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('doc_ver_com', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('doc_ver_usr', models.CharField(blank=True, default=None, max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Verification',
                'verbose_name_plural': "Verification's",
            },
        ),
    ]
