# Generated by Django 3.1.2 on 2020-11-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land_data',
            name='id',
        ),
    ]
