# Generated by Django 3.1.2 on 2020-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0003_land_data_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_data',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
