# Generated by Django 3.1.2 on 2020-11-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0004_auto_20201123_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_data',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
