# Generated by Django 3.1.2 on 2020-11-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0005_auto_20201123_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('project_id', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('payment_status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
