# Generated by Django 3.1.2 on 2020-11-24 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Land_Data', '0009_auto_20201125_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_data',
            name='project_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Land_Data.applied_data'),
        ),
        migrations.AlterField(
            model_name='payment_data',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
