# Generated by Django 3.1.2 on 2020-11-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0011_auto_20201125_0203'),
    ]

    operations = [
        migrations.AddField(
            model_name='land_data',
            name='payment_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
