# Generated by Django 3.1.2 on 2020-11-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0012_land_data_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_data',
            name='payment_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
