# Generated by Django 3.1.2 on 2020-11-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0013_auto_20201125_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='land_data',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='applied_data',
            name='monthly_charge',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
