# Generated by Django 3.1.2 on 2020-11-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0014_auto_20201125_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_data',
            name='monthly_charge',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
