# Generated by Django 3.1.2 on 2020-11-28 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Land_Data', '0015_payment_data_monthly_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_data',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='payment_data',
            name='user',
        ),
        migrations.AddField(
            model_name='payment_data',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
