# Generated by Django 3.1.2 on 2020-11-28 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0016_auto_20201128_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applied_data',
            old_name='user',
            new_name='user_id',
        ),
    ]
