# Generated by Django 3.1.2 on 2020-11-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0017_auto_20201128_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applied_data',
            name='user_id',
        ),
        migrations.AddField(
            model_name='applied_data',
            name='user',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
