# Generated by Django 3.1.2 on 2020-11-28 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0018_auto_20201128_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applied_data',
            name='project_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Land_Data.land_data'),
        ),
    ]
