# Generated by Django 3.1.2 on 2020-11-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0019_auto_20201128_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='applied_data',
            name='project_title',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
