# Generated by Django 3.1.2 on 2020-11-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0022_auto_20201128_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land_data',
            name='month',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
