# Generated by Django 3.1.2 on 2020-11-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0025_payment_data_agreement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='map_location',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
