# Generated by Django 3.1.2 on 2020-11-30 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0026_verification_map_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='map_location',
            new_name='map_Longitude',
        ),
        migrations.AddField(
            model_name='verification',
            name='map_latitude',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
