# Generated by Django 3.1.2 on 2020-11-30 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0027_auto_20201130_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='map_Longitude',
            new_name='map_longitude',
        ),
    ]
