# Generated by Django 3.1.2 on 2020-11-30 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Land_Data', '0028_auto_20201130_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='map_latitude',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='map_longitude',
        ),
        migrations.AddField(
            model_name='land_data',
            name='map_latitude',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='land_data',
            name='map_longitude',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
